main: me.noel.hu.ExperienceX
version: 1.3
name: ExperienceX
author: Noel

commands:
  mobstick:
    description: MobStick
  extroll:
    description: Troll command
  liferod:
    description: Liferod
  playerinfo:
    description: Playerinfo
  exhelp:
    description: Help of the ExperienceX plugin
  exgm:
    description: Switch your gamemode
  exdifficulty:
    description: Switch world's difficulty
  extime:
    description: Changes game time
